changed BookRepository for using JpaRepository
apanyutin/book-store pull request #3
Opened 2024-08-12 05:42 UTC by apanyutin

implemented soft delete concept for the Book entity
added Liquibase support

2024-08-12 12:27 UTC, Elena-Bruyako requested changes
see comments

2024-08-12 12:27 UTC, Elena-Bruyako commented on src/main/java/com/example/controller/BookController.java
> +@RequestMapping("/api/books")
```suggestion
@RequestMapping("/books")
```

add `server.servlet.context-path=/api` to app properties

2024-08-12 12:27 UTC, Elena-Bruyako commented on src/main/java/com/example/service/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.getTitle());
use mapstruct for this logic

2024-08-12 12:27 UTC, Elena-Bruyako commented on src/main/java/com/example/service/impl/BookServiceImpl.java
> +        Book book = bookRepository.getReferenceById(id);
https://www.baeldung.com/spring-data-jpa-getreferencebyid-findbyid-methods
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(()...
```

2024-08-13 20:34 UTC, sarakhmen approved these changes

2024-08-14 07:20 UTC, merged