added JWT support
apanyutin/book-store pull request #9
Opened 2024-08-30 14:15 UTC by apanyutin

2024-08-30 15:34 UTC, Elena-Bruyako requested changes
good job! Let's improve it

2024-08-30 15:34 UTC, Elena-Bruyako commented on src/main/java/com/example/config/OpenApiConfig.java
> +
```suggestion
```

2024-08-30 15:34 UTC, Elena-Bruyako commented on src/main/java/com/example/config/OpenApiConfig.java
> +                .components(new Components().addSecuritySchemes("BearerAuth",
create constant for strings

2024-08-30 15:34 UTC, Elena-Bruyako commented on src/main/java/com/example/security/JwtAuthFilter.java
> +    private static final String BEARER_BEGINNING = "Bearer ";
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";
```

2024-08-30 15:34 UTC, Elena-Bruyako commented on src/main/java/com/example/dto/user/UserLoginResponseDto.java
> +@Setter
```suggestion
@Getter
@Setter
```

check if you need these annotations

2024-08-31 17:16 UTC, sarakhmen approved these changes

2024-09-03 08:04 UTC, merged